"""
notify_scheduler.py - FIXED VERSION
Inshorts-style scheduled push notifications via ntfy.sh with EVEN intervals + GitHub Pages links.

FIXES:
✅ Dynamic intervals: interval = 13hrs / article_count (no more bunching)
✅ Tight 2-min send window (instead of 40-min) = 1 article per true interval  
✅ GitHub Pages deep links: https://your-site.github.io/#article-id
✅ Increased cron frequency recommended: every 5 min (still under budget)

Usage: Update GitHub cron to '*/5 3-17 * * *' for precision
"""

import os
import json
import hashlib
from datetime import datetime, timezone, timedelta
from pathlib import Path
from urllib import request as urlreq
from collections import defaultdict
import pytz  # Add to requirements.txt

IST         = pytz.timezone('Asia/Kolkata')
DIGEST_FILE = Path("docs/digest.json")
SITE_URL    = os.environ.get('SITE_URL', '').rstrip('/')

# Fixed schedule window: 9AM to 10PM IST (13 hours)
SCHEDULE_START_HOUR = 9
SCHEDULE_END_HOUR   = 22

CATEGORY_EMOJI = {
    "Politics": "🏛️", "Economy": "📊", "India": "🇮🇳", "World": "🌍",
    "Business": "💼", "Technology": "💻", "Science": "🔬", "Health": "🏥",
    "Sports": "🏆", "Law": "⚖️", "Environment": "🌿", "Infrastructure": "🏗️",
    "Education": "📚", "Culture": "🎭",
}

CATEGORY_ORDER = list(CATEGORY_EMOJI.keys())

def round_robin_articles(articles: list[dict]) -> list[dict]:
    """Round-robin across categories by importance."""
    by_cat = defaultdict(list)
    for art in articles:
        cat = art.get("category", "India")
        by_cat[cat].append(art)

    for cat in by_cat:
        by_cat[cat].sort(key=lambda a: a.get("importance", 0), reverse=True)

    ordered = [c for c in CATEGORY_ORDER if c in by_cat]
    extra = [c for c in by_cat if c not in CATEGORY_ORDER]
    cats = ordered + extra

    result = []
    while any(by_cat[c] for c in cats):
        for cat in cats:
            if by_cat[cat]:
                result.append(by_cat[cat].pop(0))
    return result

def build_precise_schedule(articles: list[dict], date_str: str) -> list[dict]:
    """Assign EXACT send times: 09:00 + (i * interval_seconds)."""
    try:
        # Matches the "%d %B %Y" generated by digest.py (e.g., "27 April 2026")
        base_date = IST.localize(datetime.strptime(date_str, "%d %B %Y"))
    except ValueError:
        try:
            # Fallback just in case the digest date format changes to short month
            base_date = IST.localize(datetime.strptime(date_str, "%d %b %Y"))
        except ValueError:
            # Ultimate fallback so the script doesn't completely crash
            base_date = datetime.now(IST).replace(hour=0, minute=0, second=0, microsecond=0)
    start = base_date.replace(hour=SCHEDULE_START_HOUR, minute=0, second=0)
    end = base_date.replace(hour=SCHEDULE_END_HOUR, minute=0, second=0)
    
    n = len(articles)
    if n == 0:
        return []

    total_seconds = int((end - start).total_seconds())
    interval_seconds = total_seconds // n  # Integer division for even spacing

    scheduled = []
    for i, art in enumerate(articles):
        send_at = start + timedelta(seconds=i * interval_seconds)
  article_id = art.get('article_id') or hashlib.md5(
    f"{art.get('date', '')}:{art['headline']}".encode()
).hexdigest()[:8]
        
        scheduled.append({
            **art,
            'article_id': article_id,  # Ensure ID exists for GitHub Pages
            '_send_at': send_at,
            '_send_at_epoch': int(send_at.timestamp()),
            '_send_at_ist': send_at.strftime("%H:%M:%S"),
            '_interval_min': f"{interval_seconds//60}:{interval_seconds%60:02d}"
        })
    return scheduled

def send_ntfy(topic: str, title: str, body: str, click_url: str, tags: list[str]) -> bool:
    """Send ntfy notification with GitHub Pages deep link."""
    headers = {
        "Title": title[:200],
        "Priority": "default",
        "Click": click_url,  # GitHub Pages article link
        "Tags": ",".join(tags),
        "Content-Type": "text/plain; charset=utf-8",
    }
    
    req = urlreq.Request(
        f"https://ntfy.sh/{topic}",
        data=body.encode("utf-8"),
        headers=headers,
        method="POST"
    )
    try:
        with urlreq.urlopen(req, timeout=10) as resp:
            return resp.status == 200
    except Exception as e:
        print(f"ntfy error: {e}")
        return False

def main():
    ntfy_topic = os.environ.get("NTFY_TOPIC", "").strip()
    if not ntfy_topic:
        print("❌ NTFY_TOPIC not set")
        return

    if not DIGEST_FILE.exists():
        print("❌ digest.json not found")
        return

    digest = json.loads(DIGEST_FILE.read_text(encoding="utf-8"))
    articles = digest.get("articles", [])
    date_str = digest.get("date", "")

    if not articles:
        print("No articles in digest")
        return

    # Build precise schedule
    ordered = round_robin_articles(articles)
    scheduled = build_precise_schedule(ordered, date_str)
    
    now_ist = datetime.now(IST)
    interval_min = int((SCHEDULE_END_HOUR - SCHEDULE_START_HOUR) * 60 / max(len(scheduled), 1))
    
    print(f"📅 {date_str} | Now: {now_ist.strftime('%H:%M:%S')} IST")
    print(f"📊 {len(scheduled)} articles | Interval: {interval_min} min")
    
    # TIGHT 2-MINUTE WINDOW (prevents bunching)
    window_start = now_ist - timedelta(minutes=1)
    window_end = now_ist + timedelta(minutes=1)
    
    due = [art for art in scheduled 
           if window_start.timestamp() <= art["_send_at_epoch"] <= window_end.timestamp()]
    
    print(f"⏰ Window: {window_start.strftime('%H:%M')}–{window_end.strftime('%H:%M')} | Due: {len(due)}")
    
    sent = 0
    for art in due:
        headline = art["headline"]
        summary = art["summary"]
        category = art.get("category", "News")
        article_id = art["article_id"]
        
        # GITHUB PAGES LINK (not Telegram)
        pages_url = f"{SITE_URL}/#article-{article_id}"
        emoji = CATEGORY_EMOJI.get(category, "📰")
        
        body = f"{emoji} {category}\n\n{summary[:350]}..."
        tags = [category.lower().replace(" ", "_"), "news", "daily"]
        
        print(f"📱 [{art['_send_at_ist']}] {headline[:60]}")
        if send_ntfy(ntfy_topic, headline, body, pages_url, tags):
            sent += 1
            print(f"   ✅ Sent → {pages_url}")
        else:
            print(f"   ❌ Failed")
    
    print(f"\n🎉 Sent {sent}/{len(due)} notifications")
    
    # Debug: Next 3 articles
    future = [a for a in scheduled if a["_send_at_epoch"] > now_ist.timestamp()]
    if future:
        print("\n⏭️  Next 3:")
        for a in future[:3]:
            print(f"   {a['_send_at_ist']} [{a.get('category')}] {a.get('headline')[:50]}")

if __name__ == "__main__":
    main()
